# version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vibechat-backend
    env_file:
      - ./.env
    environment:
      HOST: 0.0.0.0
      PORT: 5000
      DATABASE_PATH: database/vibechat.db
    ports:
      - "5006:5000"
    volumes:
      - ./backend/database:/app/database
    networks:
      - vibechat-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vibechat-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - vibechat-network
    restart: unless-stopped

networks:
  vibechat-network:
    driver: bridge
